### ISSUE TITLE
最新版无法使用

### ISSUE THREAD

**Issue by LocksonJu** [swim2sun/Douban-Movie-Workflow#2]
Alfred v3.3
最近无法使用，debug显示
`[2017-08-01 11:46:49][input.scriptfilter] <items />`
看不懂，求助

**Comment by swim2sun** [comment]
@LocksonJu 感谢反馈，无法使用的原因是豆瓣电影网站进行了改版。最新版已释出，请前往下载。[v2.0](https://github.com/swim2sun/Douban-Movie-Workflow/releases/tag/v2.0)
